name: CI

on: push

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Read JSON File
        id: property
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'version.json'
          prop_path: 'deployType'

      - run: echo ${{steps.property.outputs.prop}} 
      
      - name: Check Standard Checkout deployment type
        if: ${{steps.property.outputs.prop == 'Standard'}}
        run: | 
          echo "Triggering standard cehckout deployment"
          echo '${{ env.DEPLOYMENT_TYPE }}'
          
      - name: Calcualte Math
        id: double-conversion
        run: |
          cov=77.09890
          brCov=$(echo "scale=2; $cov*100" | bc)
          echo "BRANCH_COVERAGE_DOUBLE=${brCov}" >> $GITHUB_OUTPUT
          
      - name: Extract the UTs data
        id: ut-numbers
        run: |
          
          overallUt="939:	 Executed 97 tests, with 0 failures (0 unexpected) in 0.140 (0.160) seconds"
          trimPrefix=${{overallUt  | cut -d " " -f 9-}}
          trimSuffix=${{trimPrefix | cut -f1 -d"("}}
          echo trimSuffix
        
      - run: |
          echo "Coverted value: ${{ steps.double-conversion.outputs.BRANCH_COVERAGE_DOUBLE }}"
      
      - name: Check Custom Checkout deployment type
        env:
          DEPLOYMENT_TYPE: ${{steps.property.outputs.prop}} 
        if: ${{steps.property.outputs.prop == 'Custom'}}
        run: | 
          echo "Triggering custom cehckout deployment"
          echo '${{ env.DEPLOYMENT_TYPE }}'
        
