name: CI

on: push

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Read JSON File
        id: property
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'version.json'
          prop_path: 'deployType'

      - run: echo ${{steps.property.outputs.prop}} 
      
      - name: Check deployment type
        env:
          DEPLOYMENT_TYPE: ${{steps.property.outputs.prop}} 
        if: (${{env.DEPLOYMENT_TYPE}} == 'Standard')
        run: echo "Triggering standard cehckout deployment"
        
      - name: Check deployment type
        env:
          DEPLOYMENT_TYPE: ${{steps.property.outputs.prop}} 
        if: (${{env.DEPLOYMENT_TYPE}} == 'Custom')
        run: echo "Triggering Custom cehckout deployment"
        
